# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  snyk: snyk/snyk@2.0.2
  
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
    
  sonarqube:
      working_directory: ~/build
      docker:
        - image: sonarsource/sonar-scanner-cli
      resource_class: small
      steps:
        - run: apk update
        - run: apk upgrade
        - run: apk --no-cache add --update openssh git curl
        - checkout
        - run: find .
        - attach_workspace:
            at: ~/workspace
        - run: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
            echo "Sonar branch value is: " $SONAR_BRANCH
            echo "Sonar org value is : " $SONAR_ORGANIZATION
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORGANIZATION" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main-workflow:
    jobs:
      - build
      - sonarqube
